README.rst

Added a section about what happens if you forget to include `~ EOI` in your rules.
This caught me out the first time I used parboiled2. See my [SO question](http://stackoverflow.com/q/28343029/110856).

Extend the Common Mistakes section in the README

---

README.rst

I recently ran into this and found #61, which suggests I'm not the only person to have completely misunderstood how to use the `!` operator.

Explain how to advance with negative syntactic predicate

---

build.sbt
project/plugins.sbt

Getting the ball rolling with this initial PR just for the SBT-side.

Configure build for Scala.JS.

---

examples/src/main/scala/org/parboiled2/examples/SimpleLanguage.scala
examples/src/test/scala/org/parboiled2/examples/SimpleLanguageSpec.scala

Like #132, I didn't find a lot of examples. I made this some weeks ago when I tried out parboiled2 and thought I might be helpful.
Let me know what you think!

Add a simple programming language example

---

examples/src/main/scala/org/parboiled2/examples/SimpleSqlParser.scala
examples/src/test/scala/org/parboiled2/examples/SimpleSqlParser.scala

I was having trouble finding examples of using the library to selectively extract tokens from a document & ended up writing a very simple example. Hopefully this will help other folks like myself in the future.

A basic parser showing showing BNF & highlighting the parse tree

---

parboiled-core/src/main/scala/org/parboiled2/Parser.scala
parboiled-core/src/main/scala/org/parboiled2/RuleDSLBasics.scala
parboiled-core/src/main/scala/org/parboiled2/support/OpTreeContext.scala
parboiled-core/src/test/scala/org/parboiled2/BasicSpec.scala

fixes https://github.com/sirthias/parboiled2/issues/184

Implement `valueMap` with `ignoreCase`

---

.travis.yml
build.sbt
jsonBenchmark/src/main/scala/org/parboiled/examples/JsonParserBenchmark.scala
parboiled-core/src/main/scala/org/parboiled2/ErrorFormatter.scala
parboiled-core/src/main/scala/org/parboiled2/support/OpTreeContext.scala
parboiled-core/src/test/scala/org/parboiled2/ActionSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CalculatorSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CharPredicateSpec.scala
parboiled/src/main/scala/org/parboiled2/DynamicRuleDispatch.scala
project/plugins.sbt

Note: I've had to remove argonaut from the JMH benchmarks as it has not been released against Scala 2.13 yet.

Build for Scala 2.13.0-M4

---

parboiled-core/src/test/scala/org/parboiled2/BasicSpec.scala
parboiled-core/src/test/scala/org/parboiled2/VarianceSpec.scala

This will help getting rid of shapeless, probably needed for https://github.com/sirthias/parboiled2/issues/210

remove need for shapeless.illTyped

---

parboiled-core/src/main/scala-2/org/parboiled2/ParserMacros.scala
parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala
parboiled-core/src/test/scala/org/parboiled2/RunningSpec.scala
parboiled-core/src/test/scala/org/parboiled2/TestParserSpec.scala

The `RunningSpec` test has been simplified a bit because not all combinators are available yet

`run` macro for Scala 3

---

parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala

use more quote matches

---

parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala

optimization for string constants

---

parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala
parboiled-core/src/test/scala/org/parboiled2/ActionSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CharPredicateSpec.scala

Not much new code, seems to be mostly shared with Action.
/cc @yanns

Implement RunActions

---

parboiled-core/src/main/scala-2/org/parboiled2/support/OpTreeContext.scala
parboiled/src/main/scala/org/parboiled2/DynamicRuleDispatch.scala

Fix Scala 2 compilation errors

---

parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala

@jrudolph not sure if it's sufficient or if there was other optimizations. As I can understand the code, it's mainly about catching and reporting bad rules.

optimize Times

---

build.sbt

spray-json available in scala3

---

build.sbt

update to Scala 3.1.1

---

parboiled/src/main/scala/org/parboiled2/Base64Parsing.scala

To avoid uncessary changes for Scala 3

Simplify Base64Parsing

---

parboiled-core/src/main/scala-2/org/parboiled2/support/OpTreeContext.scala
parboiled-core/src/main/scala-3/org/parboiled2/support/OpTreeContext.scala

Fix https://github.com/sirthias/parboiled2/issues/319

ZeroOrMore: avoid instantiating builder when no match

---

parboiled/src/main/scala-2/org/parboiled2/DynamicRuleDispatchMacro.scala
parboiled/src/main/scala/org/parboiled2/DynamicRuleDispatch.scala

This PR is a performance improvement that Pekko (from fork of Akka) did to their internal parboiled2 which is now being upstreamed (for context see https://github.com/apache/incubator-pekko-http/commit/14f5ae3cbb50240b25f60dda8182284a0776d1a2).
Changes are exactly the same from the original commit.

Split out looking up and invoking rule

---

parboiled/src/main/scala-3/org/parboiled2/DynamicRuleDispatchMacro.scala

Resolves: https://github.com/sirthias/parboiled2/issues/424, fixes a regression from https://github.com/sirthias/parboiled2/pull/419
Taken from @jrudolph work on the scala3 branch for akka/pekko-http (see https://github.com/apache/incubator-pekko-http/blob/scala-3/pekko-parsing/src/main/scala-3/akka/parboiled2/DynamicRuleDispatchMacro.scala)

Update DynamicRuleDispatchMacro to work with Scala 3

---

.git-blame-ignore-revs

Add scalafmt to .git-blame-ignore-revs

---

build.sbt

Very minor change but this makes code easier to read.

Improve readability of Scala3 detection

---

build.sbt

- fix https://github.com/sirthias/parboiled2/issues/483

enable scala-native windows test
