sirthias/parboiled2

build.sbt
project/plugins.sbt

Hi. 
Could you merge this pull request just to enable OSGi manifests for your library? 
Also could you be so kind to OSGify parbolied v1, just to enable Spray to work in OSGi containers? Here is my pull request for parboiled v1: https://github.com/sirthias/parboiled/pull/92

OSGi manifests via sbt-osgi plugin

---

parboiled-core/src/main/scala/org/parboiled2/CharPredicate.scala

Now the method is implemented similarly to `and`

Fix #167 (`andNot` implementation)

---

CHANGELOG
build.sbt

The published Scala.JS build for Scala 2.12, doesn't work. Attempts to use it result in linking errors due to `org/parboiled2/CharPredicate$.sjsir` being missing from the artifact. This fixes that.

Fix Scala.js build for Scala 2.12

---

build.sbt
project/plugins.sbt

Added SBT-OSGi to allow Parboiled2 to generate an OSGi valid JAR artifact on publish or publishLocal, this allowed Parboiled2 to be used within an OSGi environment. Look at the file MANIFEST.MF inside the artifact JAR (result of publishLocal) before and after this change was added to see the changes. The change is that there are import and export packages defined there which allows OSGi to work out what imports and exports the JAR defines.

Added SBT-OSGi to allow Parboiled2 to generate an OSGi valid JAR artifact

---

parboiled-core/src/main/scala/org/parboiled2/Parser.scala
parboiled-core/src/test/scala/org/parboiled2/BasicSpec.scala

Fixes #136
By checking keys from longest to shortest, we ensure that we always
select the longest matching key.
This fix requires sorting the keys each time the rule is invoked. If
#115 gets implemented, this could be improved to make use of it instead.

Select the longest matching key in matchMap

---

.travis.yml
build.sbt
examples/src/test/scala/org/parboiled2/examples/CsvParserSpec.scala
examples/src/test/scala/org/parboiled2/examples/JsonParserSpec.scala
parboiled-core/src/test/scala/org/parboiled2/ActionSpec.scala
parboiled-core/src/test/scala/org/parboiled2/BasicSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CalculatorSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CharPredicateSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CharUtilsSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CombinatorSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CustomCharAndStringExpansionSpec.scala
parboiled-core/src/test/scala/org/parboiled2/CutSpec.scala
parboiled-core/src/test/scala/org/parboiled2/DefaultArgumentsSpec.scala
parboiled-core/src/test/scala/org/parboiled2/ErrorReportingSpec.scala
parboiled-core/src/test/scala/org/parboiled2/MetaRuleSpec.scala
parboiled-core/src/test/scala/org/parboiled2/ReductionTypeSpec.scala
parboiled-core/src/test/scala/org/parboiled2/RunSubParserSpec.scala
parboiled-core/src/test/scala/org/parboiled2/RunningSpec.scala
parboiled-core/src/test/scala/org/parboiled2/TailrecSpec.scala
parboiled-core/src/test/scala/org/parboiled2/TestParserSpec.scala
parboiled-core/src/test/scala/org/parboiled2/ValueStackSpec.scala
parboiled-core/src/test/scala/org/parboiled2/nestedpackage/AlienPackageParserSpec.scala
parboiled-core/src/test/scala/org/parboiled2/util/Base64Spec.scala
parboiled/src/test/scala/org/parboiled2/Base64ParsingSpec.scala
parboiled/src/test/scala/org/parboiled2/DynamicRuleDispatchSpec.scala
project/plugins.sbt
scalaParser/src/test/scala/scalaparser/RealSourcesSpec.scala
scalaParser/src/test/scala/scalaparser/SnippetSpec.scala

fixes #198  
This PR 
* removes specs2 in favor of utest 
* adds scala native build

scalanative + utest - specs2

---

parboiled/src/main/scala/org/parboiled2/Base64Parsing.scala
parboiled/src/test/scala/org/parboiled2/Base64ParsingSpec.scala

@adriaanm discovered that Base64 parsing wasn't being exercised as expected: https://github.com/http4s/parboiled2/pull/10
When corrected, the block tests failed.  This is fixed, though a deprecation of the existing rule was necessary to maintain binary compatibility.  I also added an `EOI` to preclude trailing junk.

 Fix Base64Parsing for blocks and extra characters

---

parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala

And also because it simplifies the AST construction.
WDYT, @yanns? Would be good to merge this first otherwise, we'll get lots of conflicts.

retain OpTreeContext structure for consistency with scala-2 

---

parboiled-core/src/main/scala-3/org/parboiled2/ParserMacros.scala

infer context for name derivation using `Symbol.spliceOwner`

---

parboiled-core/src/test/scala/org/parboiled2/ReductionTypeSpec.scala

aside from adding `.apply` to constructors, the most important bit is to
add the type annotation to the `foo1` rule
/cc @yanns

fix ReductionTypeSpec

---

build.sbt

Fortunately, it seems in the latest Scala 3 nightlies the problems have been fixed and tests that worked with 3.0.1 now work again!
/cc @yanns

use latest 3.1.1-RC1 snapshot

---

parboiled-core/src/main/scala/org/parboiled2/CharPredicate.scala

This PR is a performance improvement that Pekko (from fork of Akka) did to their internal parboiled2 which is now being upstreamed (for context see https://github.com/apache/incubator-pekko-https://github.com/apache/incubator-pekko-http/commit/1a50f8afd1f21b2c686b8015034a12a1fed47ce1).
The only change that wasn't done was making `CharPredicate` private (which isn't applicable here)
@jrudolph

Don't extend from Char => Boolean for CharPredicate

---

parboiled-core/src/main/scala/org/parboiled2/CharPredicate.scala
parboiled-core/src/test/scala/org/parboiled2/CharPredicateSpec.scala

The change in https://github.com/sirthias/parboiled2/pull/417 broken the test due to introduction of explicit apply.

Fix broken CharPredicateSpec and format CharPredicate

---

parboiled-core/src/main/scala/org/parboiled2/Parser.scala

This PR is a performance improvement that Pekko (from fork of Akka) did to their internal parboiled2 which is now being upstreamed (for context see https://github.com/apache/incubator-pekko-http/commit/d3b1322d4526171370935ec7b4648bc45fabc672).
The changes are exactly the same, the only difference is https://github.com/apache/incubator-pekko-http/commit/d3b1322d4526171370935ec7b4648bc45fabc672#diff-f223a66f93d7d04295162c661f633c286badfbb5f1eb1ae293de9c4a19f65f97R95. Not entirely sure why this function was made `final`, my initial suspicions was to prevent overriding (which can hurt performance) and also give the JVM a hint to inline this sooner (at first glance JVM should inline this eventually, the `final` would just make it happen sooner). If changing it to `final def` is necessary it …

Reuse ValueStack to avoid extra allocations

---

.github/workflows/ci.yml
.github/workflows/format.yml
build.sbt

This PR puts scalafmt into its own explicit github workflow, this method of checking if the codebase is formatted has the following advantages
* Since the scalafmt'ing is now its own workflow, it can be added as a github status check to make it impossible to merge PR's that aren't formatted
* This also means that you can remove the `scalafmtOnCompile` which I personally hate because it always messed up with IDE's/editors (i.e. they complain about a change of whats in memory vs whats formatted on disk)
* The formatter uses scalafmt-native which means its incredibly fast. The github actions pipeline to check if a codebase is formatted typically takes 5-10 seconds, providing very quick feedback to people opening PR's if they forgot to format a codebase
*  Its also done concurrently to the …

Make scalafmt explicit github actions workflow

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt
version.sbt

This PR sets up the project so that to make a proper release you only need to push a tag (i.e. for the next release you would push a tag named `v2.4.2`) and everything else is handled, i.e. a github action will trigger that will build and publish the entire project using JDK 1.8. Additionally snapshots will also be made whenever a PR is merged to `master`.
One thing that works slightly differently is the `version`. As you may have noticed `version.sbt` is deleted, this is because sbt-ci-release uses [sbt-dynver](https://github.com/sbt/sbt-dynver) to generate the version of the project automatically via git tags. In more detail, if the current git status is as at a tag you will get the full version (i.e. `v2.4.1`) however if your current git status is not at a tag then sbt-dynver will …

Setup release through sbt-github-actions and sbt-ci-release

---

project/plugins.sbt

I think I found the cause of the publishing problem, we had explicit sbt plugins listed in `project/plugins.sbt`  which was overriding the plugin versions brought by `sbt-ci-release`. In particular sbt-gpg was really ancient and for this reason wasn't setting the `loopback` flag appropriately for gpg causing the `gpg: key XXX: error sending to agent: Inappropriate ioctl for device`. This has since been fixed in newer versions of sbt-gpg. sbt-sonatype is also brought in by sbt-ci-release so no reason to provide it explicitly.
@sirthias

Remove old sbt plugins

---

.github/workflows/ci.yml
build.sbt

This PR adds windows to the ci matrix. I presume that since Parboiled2 is used in some critical Scala OS components, making sure it works on windows is a good idea. On the other hand it does explode the CI matrix a bit, so I understand if you don't want to merge the PR.
Only other additional thing to note is that `githubWorkflowOSes` has no effect on what OS is used to pubish Parboild2, this will always be hardcoded against `ubuntu-latest`.

Add windows-latest to ci matrix

---

build.sbt

This is a quality of life change, currently the name of the root project is just `root` which means when used in IDE's like Intellij its unclear what project you have open (see screenshot)
With this change you actually get an idea of what you have open
Note that this change doesn't effect the project in any meaningful way since the `root` project is not published (i.e. `publish / skip := true`)

Rename root project to parboiled2-root

---

build.sbt

This PR adds the inliner for Scala 2.12/Scala 2.13. Although in its earlier years the Scala inliner got a bad name/reputation, the current/improved Scala inliner which is found in the later versions of Scala 2.12/2.13 is considered much more comprehensive and importantly safe. As an example it will actually warn if you happen to use the `@inline` annotation and it fails to inline a statement. wrt to the statement about safety, the inliner is safe enough that it is enabled by default for scala modules (see https://github.com/scala/sbt-scala-module/blob/main/src/main/scala/ScalaModulePlugin.scala#L51-L60).
While ordinarily you would use `-opt-inline-from:<sources>` since its whats recommended for libraries, from https://docs.scala-lang.org/overviews/compiler-options/optimizer.html
> …

Add inliner for Scala 2.12/Scala2.13

---

.github/workflows/ci.yml
build.sbt

This is currently a WIP PR to test out if there are any potential issues with Scala 3.3 by using RC3. Once Scala 3.3 is properly released I will update this PR.
Scala 3.3 is a big release since its LTS, which means it will be supported for a long time (critical bugs/security fixes will be backported to the 3.3 branch) so its a good idea to prune out any potential issues before the release is made.

Update to Scala 3.3 LTS

---

build.sbt

The newer versions of sonatype use bundle deployments which needs to be setup (see https://github.com/xerial/sbt-sonatype/issues/103#issuecomment-530160058).
A quick explanation of bundle deployments is that they are atomic, i.e. you first upload the entire package (which can contain multiple artifacts/jars) and then you deploy that package all at once.
This is only done for non snapshot releases which is why we didn't get a problem earlier.
@sirthias

Setup publishing with sonatype bundle

---

.github/workflows/ci.yml
build.sbt

The latest version of sbt-github-actions already has this fix (see https://github.com/sbt/sbt-github-actions/pull/146). The PR also removes the duplicates which were introduced in https://github.com/sirthias/parboiled2/pull/459

Use githubWorkflowWindowsPagefileFix from newest sbt-github-actions

---

build.sbt

Thanks to @nafg who suggested this when working on another project.
You can verify this works by running `+publishLocal` and checking the POM manually

Simpler solution to filter out POM dependency

---

.gitignore
build.sbt

This is my first time working with sbt and  I'm not sure if I did the right things. 
I followed the approach used by scala: https://github.com/scala/scala/commit/dd1631348ddf17ae74b9759dd674ef1b80f54ecb
I'm not sure if the module name is appropriate and if we should provide a module name for the native and the js distribution also.

Add Automatic-Module-Name attribute to JVM distribution

---

.github/workflows/format.yml

Since `scalafmt-native-action v3` the scalafmt version will be picked up from the `.scalafmt.conf` file.
see: https://github.com/jrouly/scalafmt-native-action/releases/tag/v3

Remove hard-coded scalafmt version

---

build.sbt

Since the Scala2 optimizer can cause issues with incremental compilation this change means the flags will only run in CI (which also includes releasing since its also been setup for CI)

Only run the optimizer in CI
